services:
  mysql-identity:
    image: mysql:8
    container_name: mysql-identity
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: identity_db
    ports:
      - "3309:3306"
    volumes:
      - mysql-identity-data:/var/lib/mysql

volumes:
  mysql-identity-data:
